### ISSUE TITLE
Ran into a `Debug.crash` in module `VirtualDom.Metadata`

### ISSUE THREAD

**Issue by puruzio** [elm-lang/virtual-dom#69]
Elm compiler didn’t have any issue, but Chrome devtool shows this error
```
Uncaught Error: Ran into a `Debug.crash` in module `VirtualDom.Metadata`
This was caused by the `case` expression between lines 229 and 239.
One of the branches ended with a crash and the following value got through:

    Err "Expecting an object with a field named `message` at _.types but instead got: null"

The message provided by the code author is:

    Compiler is generating bad metadata. Report this at <https://github.com/elm-lang/virtual-dom/issues>.
    at http://localhost:3000/js/index.js:3100:10
    at _elm_lang$virtual_dom$VirtualDom_Metadata$decode (http://localhost:3000/js/index.js:11913:10)
    at Function.func (http://localhost:3000/js/index.js:13363:16)
    at A2 (http://localhost:3000/js/index.js:1652:12)
    at init (http://localhost:3000/js/index.js:13693:13)
    at http://localhost:3000/js/index.js:9334:12
    at Object.fullscreen [as embed] (http://localhost:3000/js/index.js:9475:5)
    at Object.<anonymous> (http://localhost:3000/js/index.js:88:24)
    at __webpack_require__ (http://localhost:3000/js/index.js:20:30)
    at http://localhost:3000/js/index.js:40:18

(anonymous function) @ index.js:3100_
elm_lang$virtual_dom$VirtualDom_Metadata$decode @ index.js:11913
(anonymous function) @ index.js:13363
A2 @ index.js:1652
init @ index.js:13693
(anonymous function) @ index.js:9334
fullscreen @ index.js:9475
(anonymous function) @ index.js:88__
webpack_require__ @ index.js:20
(anonymous function) @ index.js:40
(anonymous function) @ index.js:43
```

**Comment by evancz** [comment]
Not sure how to do anything about this without an http://sscce.org/. If you can make an SSCCE, please open a new issue with that information!

**Comment by rrosenfeld** [comment]
For others hitting this I had a very similar message and stacktrace.  I was able to resolve it by deleting elm-stuff/build-artifacts.
